name = "School Modpack"
author = "MrurBo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c1c1ba05637cc747a2e69921196896fa1615d66ce57678ecc5072356d2b1183e"

[versions]
fabric = "0.19.3"
minecraft = "1.20.1"
