name = "School Modpack"
author = "MrurBo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dec29cf45fa42754266caebb4c9a85b706c80478ab3432e21f36edbfb54a0a46"

[versions]
fabric = "0.19.3"
minecraft = "1.20.1"
