name = "School Modpack"
author = "MrurBo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ee293fac7a1a60f9b1f0f9776d8e194fd01c4d2e78358cd25b32482075cd4753"

[versions]
fabric = "0.19.3"
minecraft = "1.20.1"
